[default]
src = 'foundry/src'
test = 'foundry/test'
out = 'foundry/out'
libs = ["foundry/lib"]

[ci]
src = 'foundry/src'
out = 'foundry/out'
test = 'foundry/test'
libs = ['foundry/lib']
fuzz_runs = 512
