/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface PocketFaucetInterface extends utils.Interface {
  functions: {
    "CHILD_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "PARENT_ROLE()": FunctionFragment;
    "WITHDRAW_ROLE()": FunctionFragment;
    "addChild(uint256,uint256,address)": FunctionFragment;
    "addFunds(uint256,address)": FunctionFragment;
    "changeChildAddress(address,address)": FunctionFragment;
    "changeConfig(uint256,uint256,address)": FunctionFragment;
    "changeParentAddr(address,address)": FunctionFragment;
    "childToConfig(address)": FunctionFragment;
    "claim()": FunctionFragment;
    "getNumberChildren(address)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "parentToChildren(address,uint256)": FunctionFragment;
    "removeChild(address)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setActive(bool,address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "withdrawCoin(uint256)": FunctionFragment;
    "withdrawFundsFromChild(uint256,address)": FunctionFragment;
    "withdrawToken(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CHILD_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "PARENT_ROLE"
      | "WITHDRAW_ROLE"
      | "addChild"
      | "addFunds"
      | "changeChildAddress"
      | "changeConfig"
      | "changeParentAddr"
      | "childToConfig"
      | "claim"
      | "getNumberChildren"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "parentToChildren"
      | "removeChild"
      | "renounceRole"
      | "revokeRole"
      | "setActive"
      | "supportsInterface"
      | "withdrawCoin"
      | "withdrawFundsFromChild"
      | "withdrawToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CHILD_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARENT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAW_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addChild",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addFunds",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeChildAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeConfig",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeParentAddr",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "childToConfig",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getNumberChildren",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "parentToChildren",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "removeChild", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setActive",
    values: [boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCoin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFundsFromChild",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "CHILD_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARENT_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAW_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addChild", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeChildAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeParentAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "childToConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNumberChildren",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parentToChildren",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeChild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFundsFromChild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;

  events: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "childAdded(address,address)": EventFragment;
    "childRemoved(address,address)": EventFragment;
    "coinWithdrawed(uint256)": EventFragment;
    "configChanged(bool,uint256,address)": EventFragment;
    "fundsAdded(address,uint256,address)": EventFragment;
    "fundsWithdrawn(address,uint256,address)": EventFragment;
    "moneyClaimed(address,uint256)": EventFragment;
    "parentChanged(address,address)": EventFragment;
    "tokenWithdrawed(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "childAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "childRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "coinWithdrawed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "configChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "fundsAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "fundsWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "moneyClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "parentChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "tokenWithdrawed"): EventFragment;
}

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface childAddedEventObject {
  parent: string;
  child: string;
}
export type childAddedEvent = TypedEvent<
  [string, string],
  childAddedEventObject
>;

export type childAddedEventFilter = TypedEventFilter<childAddedEvent>;

export interface childRemovedEventObject {
  parent: string;
  child: string;
}
export type childRemovedEvent = TypedEvent<
  [string, string],
  childRemovedEventObject
>;

export type childRemovedEventFilter = TypedEventFilter<childRemovedEvent>;

export interface coinWithdrawedEventObject {
  amount: BigNumber;
}
export type coinWithdrawedEvent = TypedEvent<
  [BigNumber],
  coinWithdrawedEventObject
>;

export type coinWithdrawedEventFilter = TypedEventFilter<coinWithdrawedEvent>;

export interface configChangedEventObject {
  active: boolean;
  ceiling: BigNumber;
  child: string;
}
export type configChangedEvent = TypedEvent<
  [boolean, BigNumber, string],
  configChangedEventObject
>;

export type configChangedEventFilter = TypedEventFilter<configChangedEvent>;

export interface fundsAddedEventObject {
  parent: string;
  amount: BigNumber;
  child: string;
}
export type fundsAddedEvent = TypedEvent<
  [string, BigNumber, string],
  fundsAddedEventObject
>;

export type fundsAddedEventFilter = TypedEventFilter<fundsAddedEvent>;

export interface fundsWithdrawnEventObject {
  parent: string;
  amount: BigNumber;
  child: string;
}
export type fundsWithdrawnEvent = TypedEvent<
  [string, BigNumber, string],
  fundsWithdrawnEventObject
>;

export type fundsWithdrawnEventFilter = TypedEventFilter<fundsWithdrawnEvent>;

export interface moneyClaimedEventObject {
  child: string;
  amount: BigNumber;
}
export type moneyClaimedEvent = TypedEvent<
  [string, BigNumber],
  moneyClaimedEventObject
>;

export type moneyClaimedEventFilter = TypedEventFilter<moneyClaimedEvent>;

export interface parentChangedEventObject {
  oldAddr: string;
  newAddr: string;
}
export type parentChangedEvent = TypedEvent<
  [string, string],
  parentChangedEventObject
>;

export type parentChangedEventFilter = TypedEventFilter<parentChangedEvent>;

export interface tokenWithdrawedEventObject {
  token: string;
  amount: BigNumber;
}
export type tokenWithdrawedEvent = TypedEvent<
  [string, BigNumber],
  tokenWithdrawedEventObject
>;

export type tokenWithdrawedEventFilter = TypedEventFilter<tokenWithdrawedEvent>;

export interface PocketFaucet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PocketFaucetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CHILD_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    PARENT_ROLE(overrides?: CallOverrides): Promise<[string]>;

    WITHDRAW_ROLE(overrides?: CallOverrides): Promise<[string]>;

    addChild(
      ceiling: BigNumberish,
      periodicity: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addFunds(
      amount: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeChildAddress(
      oldAddr: string,
      newAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeConfig(
      ceiling: BigNumberish,
      periodicity: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeParentAddr(
      oldAddr: string,
      newAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    childToConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber, string] & {
        active: boolean;
        balance: BigNumber;
        ceiling: BigNumber;
        lastClaim: BigNumber;
        periodicity: BigNumber;
        parent: string;
      }
    >;

    claim(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getNumberChildren(
      parent: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    parentToChildren(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    removeChild(
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setActive(
      active: boolean,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    withdrawCoin(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawFundsFromChild(
      amount: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawToken(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  CHILD_ROLE(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  PARENT_ROLE(overrides?: CallOverrides): Promise<string>;

  WITHDRAW_ROLE(overrides?: CallOverrides): Promise<string>;

  addChild(
    ceiling: BigNumberish,
    periodicity: BigNumberish,
    child: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addFunds(
    amount: BigNumberish,
    child: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeChildAddress(
    oldAddr: string,
    newAddr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeConfig(
    ceiling: BigNumberish,
    periodicity: BigNumberish,
    child: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeParentAddr(
    oldAddr: string,
    newAddr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  childToConfig(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, BigNumber, BigNumber, string] & {
      active: boolean;
      balance: BigNumber;
      ceiling: BigNumber;
      lastClaim: BigNumber;
      periodicity: BigNumber;
      parent: string;
    }
  >;

  claim(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getNumberChildren(
    parent: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  parentToChildren(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  removeChild(
    child: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setActive(
    active: boolean,
    child: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  withdrawCoin(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawFundsFromChild(
    amount: BigNumberish,
    child: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawToken(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CHILD_ROLE(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    PARENT_ROLE(overrides?: CallOverrides): Promise<string>;

    WITHDRAW_ROLE(overrides?: CallOverrides): Promise<string>;

    addChild(
      ceiling: BigNumberish,
      periodicity: BigNumberish,
      child: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addFunds(
      amount: BigNumberish,
      child: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeChildAddress(
      oldAddr: string,
      newAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeConfig(
      ceiling: BigNumberish,
      periodicity: BigNumberish,
      child: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeParentAddr(
      oldAddr: string,
      newAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    childToConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber, string] & {
        active: boolean;
        balance: BigNumber;
        ceiling: BigNumber;
        lastClaim: BigNumber;
        periodicity: BigNumber;
        parent: string;
      }
    >;

    claim(overrides?: CallOverrides): Promise<void>;

    getNumberChildren(
      parent: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    parentToChildren(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    removeChild(child: string, overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setActive(
      active: boolean,
      child: string,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    withdrawCoin(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFundsFromChild(
      amount: BigNumberish,
      child: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawToken(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;

    "childAdded(address,address)"(
      parent?: string | null,
      child?: string | null
    ): childAddedEventFilter;
    childAdded(
      parent?: string | null,
      child?: string | null
    ): childAddedEventFilter;

    "childRemoved(address,address)"(
      parent?: string | null,
      child?: string | null
    ): childRemovedEventFilter;
    childRemoved(
      parent?: string | null,
      child?: string | null
    ): childRemovedEventFilter;

    "coinWithdrawed(uint256)"(amount?: null): coinWithdrawedEventFilter;
    coinWithdrawed(amount?: null): coinWithdrawedEventFilter;

    "configChanged(bool,uint256,address)"(
      active?: null,
      ceiling?: null,
      child?: string | null
    ): configChangedEventFilter;
    configChanged(
      active?: null,
      ceiling?: null,
      child?: string | null
    ): configChangedEventFilter;

    "fundsAdded(address,uint256,address)"(
      parent?: string | null,
      amount?: null,
      child?: null
    ): fundsAddedEventFilter;
    fundsAdded(
      parent?: string | null,
      amount?: null,
      child?: null
    ): fundsAddedEventFilter;

    "fundsWithdrawn(address,uint256,address)"(
      parent?: string | null,
      amount?: null,
      child?: null
    ): fundsWithdrawnEventFilter;
    fundsWithdrawn(
      parent?: string | null,
      amount?: null,
      child?: null
    ): fundsWithdrawnEventFilter;

    "moneyClaimed(address,uint256)"(
      child?: string | null,
      amount?: null
    ): moneyClaimedEventFilter;
    moneyClaimed(child?: string | null, amount?: null): moneyClaimedEventFilter;

    "parentChanged(address,address)"(
      oldAddr?: string | null,
      newAddr?: null
    ): parentChangedEventFilter;
    parentChanged(
      oldAddr?: string | null,
      newAddr?: null
    ): parentChangedEventFilter;

    "tokenWithdrawed(address,uint256)"(
      token?: string | null,
      amount?: null
    ): tokenWithdrawedEventFilter;
    tokenWithdrawed(
      token?: string | null,
      amount?: null
    ): tokenWithdrawedEventFilter;
  };

  estimateGas: {
    CHILD_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    PARENT_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    WITHDRAW_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    addChild(
      ceiling: BigNumberish,
      periodicity: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addFunds(
      amount: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeChildAddress(
      oldAddr: string,
      newAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeConfig(
      ceiling: BigNumberish,
      periodicity: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeParentAddr(
      oldAddr: string,
      newAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    childToConfig(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getNumberChildren(
      parent: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parentToChildren(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeChild(
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setActive(
      active: boolean,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawCoin(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawFundsFromChild(
      amount: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawToken(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CHILD_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PARENT_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WITHDRAW_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addChild(
      ceiling: BigNumberish,
      periodicity: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addFunds(
      amount: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeChildAddress(
      oldAddr: string,
      newAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeConfig(
      ceiling: BigNumberish,
      periodicity: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeParentAddr(
      oldAddr: string,
      newAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    childToConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getNumberChildren(
      parent: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parentToChildren(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeChild(
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setActive(
      active: boolean,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawCoin(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFundsFromChild(
      amount: BigNumberish,
      child: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawToken(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
