version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5450:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_is_ready:
    image: postgres
    depends_on:
      postgres:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    logging:
      driver: none
    ports:
      - 8080:8080

volumes:
  db_data:
    driver: local
