name: Lint

on: push

jobs:
  lint:
    timeout-minutes: 15

    strategy:
      matrix:
        node: ["16.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint
