name: Unit tests

on: [pull_request, push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Pocket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain
        with:
          version: nightly

      - name: Run build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run tests
      # add rpc in env
        run: |
          forge test -f https://polygon-mainnet.g.alchemy.com/v2/qLBCKN0pvsl20MhmJ2DdyQr1RhmQ_eSK -vvv
        id: test
